#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
# Start sxhkd (the hotkey daemon)
sxhkd &

# Launch Polybar
~/.config/polybar/launch.sh &

# Start dunst notification daemon
dunst &

# Start flameshot for screenshots
flameshot &

# Start network manager applet
nm-applet &

# Set wallpaper with feh (restore last wallpaper)
[ -f ~/.config/feh/fehbg ] && ~/.config/feh/fehbg &

bspc monitor -d B V W 4 5 6 7 8 9 10

#BSPWM configuration
#bspc config border_radius        8
bspc config border_width         1
bspc config window_gap           2
bspc config single_monocle       true
bspc config split_ratio          0.618
bspc config normal_border_color "#808080"
bspc config focused_border_color "#ffffff"

